name: senotype-editor

services:
  senotype-editor:
    hostname: senotype-editor
    container_name: senotype-editor
    init: true
    restart: always
    platform: linux/amd64
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:5010/health" ]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
    ports:
      - "5010:5010"
    environment:
      - APP_CONFIG=/usr/src/app/app.cfg
    volumes:
      - ../app/instance/app.cfg:/usr/src/app/app.cfg
      - ../log:/usr/src/app/log
